### ISSUE TITLE
Crash Error

### ISSUE THREAD

**Issue by closetgeekshow** [pmarinov/rrss#13]
Loaded in my OPML export from Digg Reader, waited a couple of minutes before screen inside chrome tab went blank. Reloaded it. Tried GDrive connection, that seemed to work. Then I think I clicked on a folder and got a crash error.

I'll admit that my opml file is a beast of a file containing ~700 individual feeds is not the general use case for RSS readers but I figured I'd try out your app anyway. 

Error message I received is below.
"self.m_cb.onClientqReady is not a function

source file: app.html:0:0
stack: 
TypeError: self.m_cb.onClientqReady is not a function
    at Object.callback (rrss/connect_gdrive.js:159:25)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)"

**Comment by pmarinov** [comment]
Thank you for reporting this crash.

This is a genuine error and it will be easy to fix.

**Comment by pmarinov** [comment]
Can you please check the Console log, the error message should be there and in red color.

**Comment by pmarinov** [comment]
Another question: the blank screen, importing OPML displays a progress during the importation, have you seen it display anything meaningful or just got blank?

**Comment by pmarinov** [comment]
Crash fixed in v0.9.0
